###
# your planet news site title

title = Sinclair QL planet

###
# add some web feeds to your news site

[dilwyn]
  title = Dilwyn Jones Sinclair QL Blog
  link  = https://dilwyn2.wordpress.com/
  feed  = https://dilwyn2.wordpress.com/feed/

[q-emulator]
  title  = Q-emuLator blog
  link   = https://qemulator.blogspot.com/
  feed   = http://qemulator.blogspot.com/feeds/posts/default

[smsqe-heaven]
  title  = QL QDOS and SMSQ/E Heaven
  link   = http://qlheaven.blogspot.com/
  feed   = http://qlheaven.blogspot.com/feeds/posts/default

[quantum-technology]
  title  = Quantum Technology
  link   = http://www.hunggartorino.it/ql
  feed   = http://www.hunggartorino.it/ql/language/en/feed/

[quanta]
  title  = QUANTA
  link   = https://quanta.org.uk/
  feed   = https://quanta.org.uk/feed/

[kilgus-net]
  title  = Kilgus.net - blog
  link   = https://www.kilgus.net/
  feed   = https://www.kilgus.net/category/ql/feed/

[quantum]
  title  = Quantum Technology
  link   = https://www.hunggartorino.it/ql/language/it/
  feed   = https://www.hunggartorino.it/ql/language/it/feed

[old-machinery]
  title = Old Machinery
  url   = https://oldmachinery.blogspot.com/search/label/sinclair%20ql
  feed  = https://oldmachinery.blogspot.com/feeds/posts/default/-/sinclair%20ql?alt=rss

[ql-heaven]
  title = QL Heaven
  url   = https://qlheaven.blogspot.com/
  feed  = https://qlheaven.blogspot.com/feeds/posts/default?alt=rss

[qblog]
  title = QBlog (es)
  link  = https://sinclairqles.wordpress.com/
  feed  = https://sinclairqles.wordpress.com/feed/

[codice]
  title = Códice (es)
  url   = https://javguerra.github.io/
  feed  = https://javguerra.github.io/blog/tag/sinclair%20ql.xml

[old-8-bits]
  title = Old 8 Bits (es)
  url   = https://old8bits.blogspot.com/search/label/QL
  feed  = https://old8bits.blogspot.com/feeds/posts/default/-/QL

[speccy-org]
  title  = Foro Speccy.org (es)
  link   = https://foro.speccy.org/viewforum.php?f=15
  feed   = https://foro.speccy.org/feed.php?f=15
