###
# your planet news site title

title = Sinclair QL planet



###
# add some web feeds to your news site

[qblog]
  title = QBlog (es)
  link  = https://sinclairqles.wordpress.com/
  feed  = https://sinclairqles.wordpress.com/feed/

[dilwyn]
  title = Dilwyn Jones Sinclair QL Blog
  link  = https://dilwyn2.wordpress.com/
  feed  = https://dilwyn2.wordpress.com/feed/

[q-emulator]
  title  = Q-emuLator blog
  link   = https://qemulator.blogspot.com/
  feed   = http://qemulator.blogspot.com/feeds/posts/default

[smsqe-heaven]
  title  = QL QDOS and SMSQ/E Heaven
  link   = http://qlheaven.blogspot.com/
  feed   = http://qlheaven.blogspot.com/feeds/posts/default

[smsqe-heaven]
  title  = Quantum Technology
  link   = http://www.hunggartorino.it/ql
  feed   = http://www.hunggartorino.it/ql/language/en/feed/

[quanta]
  title  = QUANTA
  link   = https://quanta.org.uk/
  feed   = https://quanta.org.uk/feed/

[kilgus-net]
  title  = Kilgus.net - blog
  link   = https://www.kilgus.net/
  feed   = https://www.kilgus.net/blog/feed

[output]
  atom.xml = planet.starter.atom.erb
  feed.xml = planet.starter.rss.erb