name: Build and Deploy Sinclair QL Planet

on:
  schedule:
    # Se ejecuta automáticamente cada 4 horas
    - cron: '0 */4 * * *'
  push:
    # Se ejecuta inmediatamente cada vez que subes cambios a la rama principal
    branches:
      - main
      - master
  workflow_dispatch: # Permite pulsar un botón en GitHub para compilar manualmente

# Permisos requeridos para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue simultáneo
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Pluto
        run: |
          gem install pluto

      - name: Build Planet with Pluto
        run: |
          PLUTO_GEM_DIR=$(ruby -e 'puts Gem.loaded_specs["pluto"].full_gem_path')
          mkdir -p "$PLUTO_GEM_DIR/templates"
          cp -r ./planet-starter "$PLUTO_GEM_DIR/templates/planet-starter"
          pluto build planet.ini --template planet-starter -o public

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4